### ISSUE TITLE
Multiple CIDR configuration

### ISSUE THREAD

**Issue by CesarRoaldes** [Sh4d1/scaleway-k8s-vpc#15]
Hello,

First thank you for this project that is very timely for me!
Here is my issue, I'm setting up a VPC on the CIDR `192.168.0.0/24` exposed on Internet through a gateway whose ip is `192.168.0.1`. Using your controller I attach my kubernetes cluster nodes to the VPC with static IPs. The IP range must be `[192.168.0.1-192.168.0.255]` for the cluster nodes, corresponding to the following CIDR list:
```
192.168.0.2/31
192.168.0.4/30
192.168.0.8/29
192.168.0.16/28
192.168.0.32/27
192.168.0.64/26
192.168.0.128/25
```
I tried use a list for `.spec.ipam.static.cidr` value but only string are allowed. Then I tried to use the following *string list*:
`cidr: "192.168.0.3/31,192.168.0.4/30,192.168.0.8/29,192.168.0.16/28,192.168.0.32/27,192.168.0.64/26,192.168.0.128/25"`
without success. No static IP were given to the nodes on the `ens5` network interface.
Here is the manifest I'm using:
```
apiVersion: vpc.scaleway.com/v1alpha1
kind: PrivateNetwork
metadata:
  name: vpc-ens5
spec:
  id: <VPC-ID>
  ipam:
    type: Static
    static:
      cidr: "192.168.0.3/32,192.168.0.4/30,192.168.0.8/29,192.168.0.16/28,192.168.0.32/27,192.168.0.64/26,192.168.0.128/25"
  routes:
  - to: 192.168.1.0/24
    via: 192.168.0.1
```
Is it possible to setup this kind of CIDR? Did I made a mistake / misunderstand some concepts?

Thank you, in advance for your valuable assistance!

**Comment by CesarRoaldes** [comment]
Hi, [Sh4d1](https://github.com/Sh4d1) gave me an answer through another chat channel and solved my problem, thank you again 🙏 !

The solution was to use the [`availableRanges option`](https://github.com/Sh4d1/scaleway-k8s-vpc/blob/main/api/v1alpha1/privatenetwork_types.go#L69) to specify the IPs my Kubernetes nodes can take. In my case, here is the working manifest of my `PrivateNetwork`:
```yaml
apiVersion: vpc.scaleway.com/v1alpha1
kind: PrivateNetwork
metadata:
  name: <VPC-name>
spec:
  id: <VPC-id>
  ipam:
    type: Static
    static:
      cidr: "192.168.0.0/24"
      availableRanges: 
      - 192.168.0.3/32
      - 192.168.0.4/30
      - 192.168.0.8/29
      - 192.168.0.16/28
      - 192.168.0.32/27
      - 192.168.0.64/26
      - 192.168.0.128/25
  routes:
  - to: 192.168.1.0/24
    via: 192.168.0.1
```
